name: Build SHRP Recovery

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
      env:
        DEBIAN_FRONTEND: noninteractive
    
    steps:
      - name: Cleanup
        uses: rokibhasansagar/slimhub_actions@main

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          apt-get update && apt-get install -y \
          git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev \
          gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev \
          x11proto-core-dev libx11-dev lib32z-dev ccache libgl1-mesa-dev \
          libxml2-utils xsltproc unzip python3 python3-pip python-is-python3 rsync

      - name: Setup Repo
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Initialize and Sync
        run: |
          mkdir shrp
          cd shrp
          repo init -u https://github.com/SHRP/manifest.git -b v3_11.0
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

      - name: Prepare Device Tree
        run: |
          mkdir -p shrp/device/oppo/A31
          rsync -av --exclude='.github' ./ shrp/device/oppo/A31/

      - name: Build SHRP
        run: |
          cd shrp
          export ALLOW_MISSING_DEPENDENCIES=true
          source build/envsetup.sh
          lunch twrp_OP4C7D-eng
          mka recoveryimage

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SHRP_Recovery
          path: shrp/out/target/product/OP4C7D/*.img
          if-no-files-found: error
